# Generated by Django 5.0.6 on 2024-05-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_mailing_date', models.DateTimeField(auto_now_add=True, verbose_name='дата первой отправки')),
                ('frequency', models.CharField(choices=[('1', 'раз в день'), ('2', 'раз в неделю'), ('3', 'раз в месяц')], max_length=150, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('1', 'завершена'), ('2', 'создана'), ('3', 'запущена')], max_length=150, verbose_name='статус отправки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client', verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'настройки',
                'verbose_name_plural': 'настройки',
            },
        ),
    ]
