# Generated by Django 5.0.6 on 2024-05-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('mailing', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.message', verbose_name='сообщение'),
        ),
        migrations.RemoveField(
            model_name='settings',
            name='client',
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_date', models.DateTimeField(auto_now=True, verbose_name='дата последней попытки')),
                ('status', models.CharField(choices=[('1', 'успешно'), ('2', 'не успешно')], max_length=150, verbose_name='статус попытки')),
                ('server_response', models.CharField(blank=True, max_length=150, null=True, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.settings', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='client.client', verbose_name='клиент'),
        ),
    ]
