# Generated by Django 5.0.6 on 2024-05-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_settings_message_remove_settings_client_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('успешно', 'успешно'), ('не успешно', 'не успешно')], max_length=150, verbose_name='статус попытки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='frequency',
            field=models.CharField(choices=[('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=150, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('завершена', 'завершена'), ('создана', 'создана'), ('запущена', 'запущена')], max_length=150, verbose_name='статус отправки'),
        ),
    ]
