# Generated by Django 5.0.6 on 2024-05-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_attempt_status_alter_settings_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(blank=True, choices=[('успешно', 'успешно'), ('не успешно', 'не успешно')], max_length=150, null=True, verbose_name='статус попытки'),
        ),
    ]
