# Generated by Django 5.0.6 on 2024-05-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_attempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='first_mailing_date',
            field=models.DateTimeField(verbose_name='дата первой отправки'),
        ),
    ]
