# Generated by Django 5.0.6 on 2024-05-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_settings_first_mailing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='last_attempt_date',
            field=models.DateTimeField(verbose_name='дата последней попытки'),
        ),
    ]
