# Generated by Django 5.0.6 on 2024-05-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_attempt_last_attempt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='frequency',
            field=models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], max_length=150, verbose_name='периодичность'),
        ),
    ]
