# Generated by Django 4.2 on 2024-07-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_attempt_last_attempt_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'permissions': [('set_status_to_completed', 'Can disable mailing')], 'verbose_name': 'настройки', 'verbose_name_plural': 'настройки'},
        ),
    ]
